/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Faceboot.App;
import Faceboot.AppState;
import View.Components.TextPrompt;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;

/**
 *
 * @author orlandocamacho
 */
public class Register extends javax.swing.JFrame {

    private int mouseX;
    private int mouseY;
    
    /**
     * Creates new form UserRegister
     */
    public Register() {
        initComponents();
        
        new TextPrompt("Nombre", name);
        new TextPrompt("Apellido", lastname);
        new TextPrompt("Correo electrónico", email);
        new TextPrompt("Contraseña", password);
        
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 22, 22));
        
        this.comboboxSetInvisible();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        isfast = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        containerName = new View.Components.RoundedPanel();
        name = new javax.swing.JTextField();
        containerName1 = new View.Components.RoundedPanel();
        lastname = new javax.swing.JTextField();
        containerName2 = new View.Components.RoundedPanel();
        email = new javax.swing.JTextField();
        containerName3 = new View.Components.RoundedPanel();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        containerName4 = new View.Components.RoundedPanel();
        cDay = new javax.swing.JComboBox<>();
        containerName5 = new View.Components.RoundedPanel();
        cMonth = new javax.swing.JComboBox<>();
        containerName6 = new View.Components.RoundedPanel();
        cYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        containerName7 = new View.Components.RoundedPanel();
        female = new javax.swing.JRadioButton();
        containerName9 = new View.Components.RoundedPanel();
        personalized = new javax.swing.JRadioButton();
        containerName8 = new View.Components.RoundedPanel();
        male = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        containerBtn = new View.Components.RoundedPanel();
        containerBtn1 = new View.Components.RoundedPanel();
        signUp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(23, 24, 26));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Registrarte");
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/x.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        isfast.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        isfast.setForeground(new java.awt.Color(255, 255, 255));
        isfast.setText("Es rápido y fácil.");
        jPanel1.add(isfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, -1, 20));

        Content.setBackground(new java.awt.Color(23, 24, 26));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerName.setBackground(new java.awt.Color(58, 59, 60));
        containerName.setToolTipText("Correo electrónico");

        name.setBackground(new java.awt.Color(58, 59, 60));
        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setBorder(null);
        name.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerNameLayout = new javax.swing.GroupLayout(containerName);
        containerName.setLayout(containerNameLayout);
        containerNameLayout.setHorizontalGroup(
            containerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        containerNameLayout.setVerticalGroup(
            containerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(containerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 40));

        containerName1.setBackground(new java.awt.Color(58, 59, 60));
        containerName1.setToolTipText("Correo electrónico");

        lastname.setBackground(new java.awt.Color(58, 59, 60));
        lastname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(204, 204, 204));
        lastname.setBorder(null);
        lastname.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerName1Layout = new javax.swing.GroupLayout(containerName1);
        containerName1.setLayout(containerName1Layout);
        containerName1Layout.setHorizontalGroup(
            containerName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        containerName1Layout.setVerticalGroup(
            containerName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(containerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, 40));

        containerName2.setBackground(new java.awt.Color(58, 59, 60));
        containerName2.setToolTipText("Correo electrónico");

        email.setBackground(new java.awt.Color(58, 59, 60));
        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setToolTipText("");
        email.setBorder(null);
        email.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerName2Layout = new javax.swing.GroupLayout(containerName2);
        containerName2.setLayout(containerName2Layout);
        containerName2Layout.setHorizontalGroup(
            containerName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerName2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        containerName2Layout.setVerticalGroup(
            containerName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(containerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 390, 40));

        containerName3.setBackground(new java.awt.Color(58, 59, 60));
        containerName3.setToolTipText("Correo electrónico");

        password.setBackground(new java.awt.Color(58, 59, 60));
        password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setToolTipText("");
        password.setBorder(null);
        password.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerName3Layout = new javax.swing.GroupLayout(containerName3);
        containerName3.setLayout(containerName3Layout);
        containerName3Layout.setHorizontalGroup(
            containerName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        containerName3Layout.setVerticalGroup(
            containerName3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(containerName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>\nAl hacer clic en \"Registrarte\", aceptas nuestras Condiciones, la Política de\ndatos y la Política de cookies. Es posible que te enviemos notificaciones por \nSMS, que puedes desactivar cuando quieras.\n</html>"); // NOI18N
        Content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 390, 40));

        containerName4.setBackground(new java.awt.Color(58, 59, 60));
        containerName4.setToolTipText("Correo electrónico");
        containerName4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cDay.setBackground(new java.awt.Color(58, 59, 60));
        cDay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cDay.setForeground(new java.awt.Color(255, 255, 255));
        cDay.setMaximumRowCount(10);
        cDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cDay.setBorder(null);
        containerName4.add(cDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        Content.add(containerName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 120, 40));

        containerName5.setBackground(new java.awt.Color(58, 59, 60));
        containerName5.setToolTipText("Correo electrónico");
        containerName5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cMonth.setBackground(new java.awt.Color(58, 59, 60));
        cMonth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cMonth.setForeground(new java.awt.Color(204, 204, 204));
        cMonth.setMaximumRowCount(10);
        cMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cMonth.setBorder(null);
        containerName5.add(cMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        Content.add(containerName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, 40));

        containerName6.setBackground(new java.awt.Color(58, 59, 60));
        containerName6.setToolTipText("Correo electrónico");
        containerName6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cYear.setBackground(new java.awt.Color(58, 59, 60));
        cYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYear.setForeground(new java.awt.Color(204, 204, 204));
        cYear.setMaximumRowCount(10);
        cYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cYear.setBorder(null);
        containerName6.add(cYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        Content.add(containerName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 120, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de nacimiento");
        Content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        containerName7.setBackground(new java.awt.Color(58, 59, 60));
        containerName7.setToolTipText("Correo electrónico");
        containerName7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        female.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        female.setForeground(new java.awt.Color(204, 204, 204));
        female.setText("Mujer");
        female.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        female.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        female.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButton.png"))); // NOI18N
        female.setIconTextGap(25);
        female.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonHover.png"))); // NOI18N
        female.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonSelected.png"))); // NOI18N
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        containerName7.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        Content.add(containerName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, 40));

        containerName9.setBackground(new java.awt.Color(58, 59, 60));
        containerName9.setToolTipText("Correo electrónico");
        containerName9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalized.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        personalized.setForeground(new java.awt.Color(204, 204, 204));
        personalized.setText("Personalizado");
        personalized.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalized.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        personalized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButton.png"))); // NOI18N
        personalized.setIconTextGap(21);
        personalized.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonHover.png"))); // NOI18N
        personalized.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonSelected.png"))); // NOI18N
        personalized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalizedActionPerformed(evt);
            }
        });
        containerName9.add(personalized, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        Content.add(containerName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 150, 40));

        containerName8.setBackground(new java.awt.Color(58, 59, 60));
        containerName8.setToolTipText("Correo electrónico");
        containerName8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        male.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        male.setForeground(new java.awt.Color(204, 204, 204));
        male.setText("Hombre");
        male.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        male.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        male.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButton.png"))); // NOI18N
        male.setIconTextGap(30);
        male.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonHover.png"))); // NOI18N
        male.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonSelected.png"))); // NOI18N
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        containerName8.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        Content.add(containerName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, 40));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sexo");
        Content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        containerBtn.setBackground(new java.awt.Color(65, 183, 41));
        containerBtn.setLayout(new java.awt.BorderLayout());
        Content.add(containerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        containerBtn1.setBackground(new java.awt.Color(65, 183, 41));
        containerBtn1.setLayout(new java.awt.BorderLayout());

        signUp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Registrarte");
        signUp.setContentAreaFilled(false);
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        containerBtn1.add(signUp, java.awt.BorderLayout.CENTER);

        Content.add(containerBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 190, 35));
        Content.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 430, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void personalizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalizedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalizedActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        email.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_emailFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        email.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_emailFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        lastname.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        lastname.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_lastnameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        name.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_nameFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_nameFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_passwordFocusLost

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        setLocation(X - mouseX, Y - mouseY + 1);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        App.GetSingleton().SetState(AppState.Login);
    }//GEN-LAST:event_closeMousePressed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        String name = this.name.getText();
        String lastName = this.lastname.getText();
        String email = this.email.getText();
        String password = new String(this.password.getPassword());
        App.GetSingleton().RegisterController.AttemptRegister(name, lastName, email, password);
    }//GEN-LAST:event_signUpActionPerformed

    public void comboboxSetInvisible(){
        cDay.setBackground(new Color(0,0,0,0));
        cDay.setForeground(Color.red);
 
        cMonth.setBackground(new Color(0,0,0,0));

        cYear.setBackground(new Color(0,0,0,0));
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Register().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JComboBox<String> cDay;
    private javax.swing.JComboBox<String> cMonth;
    private javax.swing.JComboBox<String> cYear;
    private javax.swing.JLabel close;
    public View.Components.RoundedPanel containerBtn;
    public View.Components.RoundedPanel containerBtn1;
    private View.Components.RoundedPanel containerName;
    private View.Components.RoundedPanel containerName1;
    private View.Components.RoundedPanel containerName2;
    private View.Components.RoundedPanel containerName3;
    private View.Components.RoundedPanel containerName4;
    private View.Components.RoundedPanel containerName5;
    private View.Components.RoundedPanel containerName6;
    private View.Components.RoundedPanel containerName7;
    private View.Components.RoundedPanel containerName8;
    private View.Components.RoundedPanel containerName9;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel isfast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton personalized;
    private javax.swing.JLabel register;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
