/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Faceboot.App;
import Faceboot.AppState;
import java.awt.Color;

/**
 *
 * @author urias
 */
public class SettingsAccounts extends javax.swing.JFrame {

    private int mouseX;
    private int mouseY;
    
    /**
     * Creates new form Connections
     */
    public SettingsAccounts() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        isfast = new javax.swing.JLabel();
        isfast1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        twitter = new View.Components.RoundedPanel();
        jButton2 = new javax.swing.JButton();
        facebook = new View.Components.RoundedPanel();
        jButton1 = new javax.swing.JButton();
        containerBtnCntTw = new View.Components.RoundedPanel();
        ConnectBtnTw = new javax.swing.JButton();
        containerBtnCntFb = new View.Components.RoundedPanel();
        ConnectBtnFb1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(23, 24, 26));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Conectarse");
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/x.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        isfast.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        isfast.setForeground(new java.awt.Color(255, 255, 255));
        isfast.setText("la aplicación y administrar las cuentas vinculadas.");
        jPanel1.add(isfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        isfast1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        isfast1.setForeground(new java.awt.Color(255, 255, 255));
        isfast1.setText("Utilice las siguientes pestañas para administrar los permisos de");
        jPanel1.add(isfast1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, -1, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 440, 1));

        jPanel2.setBackground(new java.awt.Color(23, 24, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        twitter.setBackground(new java.awt.Color(45, 163, 226));
        twitter.setLayout(new java.awt.BorderLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/twitterLogin.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        twitter.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 64, 64));

        facebook.setBackground(new java.awt.Color(37, 119, 241));
        facebook.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/facebookLogin.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(64, 64));
        facebook.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 62, 63));

        containerBtnCntTw.setBackground(new java.awt.Color(37, 119, 241));
        containerBtnCntTw.setLayout(new java.awt.BorderLayout());

        ConnectBtnTw.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConnectBtnTw.setForeground(new java.awt.Color(255, 255, 255));
        ConnectBtnTw.setText("Conectar");
        ConnectBtnTw.setContentAreaFilled(false);
        ConnectBtnTw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ConnectBtnTwMouseMoved(evt);
            }
        });
        ConnectBtnTw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConnectBtnTwMouseExited(evt);
            }
        });
        ConnectBtnTw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnTwActionPerformed(evt);
            }
        });
        containerBtnCntTw.add(ConnectBtnTw, java.awt.BorderLayout.CENTER);

        jPanel2.add(containerBtnCntTw, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, 30));

        containerBtnCntFb.setBackground(new java.awt.Color(37, 119, 241));
        containerBtnCntFb.setLayout(new java.awt.BorderLayout());

        ConnectBtnFb1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConnectBtnFb1.setForeground(new java.awt.Color(255, 255, 255));
        ConnectBtnFb1.setText("Conectar");
        ConnectBtnFb1.setContentAreaFilled(false);
        ConnectBtnFb1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ConnectBtnFb1MouseMoved(evt);
            }
        });
        ConnectBtnFb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConnectBtnFb1MouseExited(evt);
            }
        });
        ConnectBtnFb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnFb1ActionPerformed(evt);
            }
        });
        containerBtnCntFb.add(ConnectBtnFb1, java.awt.BorderLayout.CENTER);

        jPanel2.add(containerBtnCntFb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed

    }//GEN-LAST:event_closeMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        setLocation(X - mouseX, Y - mouseY + 1);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void ConnectBtnTwMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectBtnTwMouseMoved
        containerBtnCntTw.setBackground(new Color(35,111,229));
    }//GEN-LAST:event_ConnectBtnTwMouseMoved

    private void ConnectBtnTwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectBtnTwMouseExited
        containerBtnCntTw.setBackground(new Color(37,119,241));
    }//GEN-LAST:event_ConnectBtnTwMouseExited

    private void ConnectBtnTwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBtnTwActionPerformed
        /*
        Iniciar sesion
        */
    }//GEN-LAST:event_ConnectBtnTwActionPerformed

    private void ConnectBtnFb1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectBtnFb1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ConnectBtnFb1MouseMoved

    private void ConnectBtnFb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectBtnFb1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ConnectBtnFb1MouseExited

    private void ConnectBtnFb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBtnFb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConnectBtnFb1ActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        App.GetSingleton().SetState(AppState.Settings);
    }//GEN-LAST:event_closeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectBtnFb1;
    private javax.swing.JButton ConnectBtnTw;
    private javax.swing.JLabel close;
    private View.Components.RoundedPanel containerBtnCntFb;
    private View.Components.RoundedPanel containerBtnCntTw;
    private View.Components.RoundedPanel facebook;
    private javax.swing.JLabel isfast;
    private javax.swing.JLabel isfast1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel register;
    private View.Components.RoundedPanel twitter;
    // End of variables declaration//GEN-END:variables
}
