/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.util.Map;
import javax.swing.BorderFactory;

/**
 *
 * @author orlandocamacho
 */
public class Login extends javax.swing.JFrame {
    
    private int mouseX;
    private int mouseY;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        String separator = File.separator;
        if (separator.equals("")) {
            setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 22, 22));
            this.DisposeButtonW.setVisible(false);
            this.MinimizeButtonW.setVisible(false);
            this.FullScreenButtonW.setVisible(false);
        } else {
            setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 0, 0));
            this.DisposeButton.setVisible(false);
            this.MinimizeButton.setVisible(false);
            this.FullScreenButton.setVisible(false);
        }

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        FacebootLogo = new javax.swing.JLabel();
        IniciarSesionCon = new javax.swing.JLabel();
        log = new View.Components.RoundedPanel();
        containerBtn = new View.Components.RoundedPanel();
        CreateAccountBt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        forgot = new javax.swing.JLabel();
        containerMail = new View.Components.RoundedPanel();
        mail = new javax.swing.JTextField();
        containerPassword = new View.Components.RoundedPanel();
        password = new javax.swing.JPasswordField();
        containerBtnLog = new View.Components.RoundedPanel();
        LogInBtn = new javax.swing.JButton();
        facebook = new View.Components.RoundedPanel();
        jButton1 = new javax.swing.JButton();
        twitter = new View.Components.RoundedPanel();
        jButton2 = new javax.swing.JButton();
        google = new View.Components.RoundedPanel();
        jButton3 = new javax.swing.JButton();
        topBar = new javax.swing.JPanel();
        DisposeButton = new javax.swing.JLabel();
        MinimizeButton = new javax.swing.JLabel();
        FullScreenButton = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        DisposeButtonW = new javax.swing.JLabel();
        FullScreenButtonW = new javax.swing.JLabel();
        MinimizeButtonW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        content.setBackground(new java.awt.Color(23, 24, 26));
        content.setPreferredSize(new java.awt.Dimension(1280, 670));

        FacebootLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FacebootLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/faceboot2.png"))); // NOI18N

        IniciarSesionCon.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        IniciarSesionCon.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesionCon.setText("Iniciar sesión con:");

        log.setBackground(new java.awt.Color(35, 36, 37));
        log.setForeground(new java.awt.Color(255, 255, 255));

        containerBtn.setBackground(new java.awt.Color(65, 183, 41));
        containerBtn.setLayout(new java.awt.BorderLayout());

        CreateAccountBt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CreateAccountBt.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountBt.setText("Crear cuenta nueva");
        CreateAccountBt.setContentAreaFilled(false);
        CreateAccountBt.setFocusPainted(false);
        CreateAccountBt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CreateAccountBtMouseMoved(evt);
            }
        });
        CreateAccountBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateAccountBtMouseExited(evt);
            }
        });
        CreateAccountBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountBtActionPerformed(evt);
            }
        });
        containerBtn.add(CreateAccountBt, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        forgot.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        forgot.setForeground(new java.awt.Color(37, 119, 241));
        forgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgot.setText("¿Olvidaste tu contraseña?");
        forgot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgotMouseMoved(evt);
            }
        });
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotMouseExited(evt);
            }
        });

        containerMail.setBackground(new java.awt.Color(58, 59, 60));
        containerMail.setToolTipText("Correo electrónico");

        mail.setBackground(new java.awt.Color(58, 59, 60));
        mail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        mail.setForeground(new java.awt.Color(153, 153, 153));
        mail.setText("Correo electrónico");
        mail.setBorder(null);
        mail.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        mail.setIgnoreRepaint(true);
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerMailLayout = new javax.swing.GroupLayout(containerMail);
        containerMail.setLayout(containerMailLayout);
        containerMailLayout.setHorizontalGroup(
            containerMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMailLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        containerMailLayout.setVerticalGroup(
            containerMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerPassword.setBackground(new java.awt.Color(58, 59, 60));
        containerPassword.setToolTipText("Contraseña");

        password.setBackground(new java.awt.Color(58, 59, 60));
        password.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("Contraseña");
        password.setBorder(null);
        password.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        password.setEchoChar('\u0000');
        password.setIgnoreRepaint(true);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerPasswordLayout = new javax.swing.GroupLayout(containerPassword);
        containerPassword.setLayout(containerPasswordLayout);
        containerPasswordLayout.setHorizontalGroup(
            containerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPasswordLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        containerPasswordLayout.setVerticalGroup(
            containerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerBtnLog.setBackground(new java.awt.Color(37, 119, 241));
        containerBtnLog.setLayout(new java.awt.BorderLayout());

        LogInBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInBtn.setText("Iniciar sesión");
        LogInBtn.setContentAreaFilled(false);
        LogInBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogInBtnMouseMoved(evt);
            }
        });
        LogInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInBtnMouseExited(evt);
            }
        });
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });
        containerBtnLog.add(LogInBtn, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout logLayout = new javax.swing.GroupLayout(log);
        log.setLayout(logLayout);
        logLayout.setHorizontalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(containerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(containerBtnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(containerMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, logLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(forgot, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        logLayout.setVerticalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(containerMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(containerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(containerBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(forgot)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(containerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        facebook.setBackground(new java.awt.Color(37, 119, 241));
        facebook.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/facebookLogin.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(64, 64));
        facebook.add(jButton1, java.awt.BorderLayout.PAGE_END);

        twitter.setBackground(new java.awt.Color(45, 163, 226));
        twitter.setLayout(new java.awt.BorderLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/twitterLogin.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        twitter.add(jButton2, java.awt.BorderLayout.CENTER);

        google.setBackground(new java.awt.Color(255, 255, 255));
        google.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/googleLogin.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        google.add(jButton3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FacebootLogo)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(IniciarSesionCon))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(facebook, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(google, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(FacebootLogo)
                        .addGap(15, 15, 15)
                        .addComponent(IniciarSesionCon)
                        .addGap(21, 21, 21)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(google, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(facebook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(136, 154, Short.MAX_VALUE))
        );

        topBar.setBackground(new java.awt.Color(31, 32, 36));
        topBar.setPreferredSize(new java.awt.Dimension(0, 35));
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DisposeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisposeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButton.png"))); // NOI18N
        DisposeButton.setMaximumSize(new java.awt.Dimension(14, 14));
        DisposeButton.setMinimumSize(new java.awt.Dimension(14, 14));
        DisposeButton.setPreferredSize(new java.awt.Dimension(14, 14));
        DisposeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DisposeButtonMouseMoved(evt);
            }
        });
        DisposeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DisposeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisposeButtonMousePressed(evt);
            }
        });
        topBar.add(DisposeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        MinimizeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/MinimizeButton.png"))); // NOI18N
        MinimizeButton.setMaximumSize(new java.awt.Dimension(14, 14));
        MinimizeButton.setMinimumSize(new java.awt.Dimension(14, 14));
        MinimizeButton.setPreferredSize(new java.awt.Dimension(14, 14));
        MinimizeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseMoved(evt);
            }
        });
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeButtonMousePressed(evt);
            }
        });
        topBar.add(MinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        FullScreenButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FullScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/FullScreenButton.png"))); // NOI18N
        FullScreenButton.setMaximumSize(new java.awt.Dimension(14, 14));
        FullScreenButton.setMinimumSize(new java.awt.Dimension(14, 14));
        FullScreenButton.setPreferredSize(new java.awt.Dimension(14, 14));
        FullScreenButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FullScreenButtonMouseMoved(evt);
            }
        });
        FullScreenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullScreenButtonMouseExited(evt);
            }
        });
        topBar.add(FullScreenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Faceboot.png"))); // NOI18N
        topBar.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 0, 145, 35));

        DisposeButtonW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DisposeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButtonW.png"))); // NOI18N
        DisposeButtonW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DisposeButtonWMouseMoved(evt);
            }
        });
        DisposeButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DisposeButtonWMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DisposeButtonWMousePressed(evt);
            }
        });
        topBar.add(DisposeButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(968, 0, 55, 33));

        FullScreenButtonW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FullScreenButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/FullScreenButtonW.png"))); // NOI18N
        FullScreenButtonW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FullScreenButtonWMouseMoved(evt);
            }
        });
        FullScreenButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullScreenButtonWMouseExited(evt);
            }
        });
        topBar.add(FullScreenButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 0, 55, 33));

        MinimizeButtonW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MinimizeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/MinimizeButtonW.png"))); // NOI18N
        MinimizeButtonW.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MinimizeButtonWMouseMoved(evt);
            }
        });
        MinimizeButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeButtonWMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MinimizeButtonWMousePressed(evt);
            }
        });
        topBar.add(MinimizeButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 0, 55, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(topBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(topBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();

        setLocation(X - mouseX, Y - mouseY + 1);
    }//GEN-LAST:event_topBarMouseDragged

    private void DisposeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonMouseMoved
        DisposeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButton2.png")));
    }//GEN-LAST:event_DisposeButtonMouseMoved

    private void DisposeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonMouseExited
        DisposeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButton.png")));
    }//GEN-LAST:event_DisposeButtonMouseExited

    private void MinimizeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseMoved
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/MinimizeButton2.png")));
    }//GEN-LAST:event_MinimizeButtonMouseMoved

    private void MinimizeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseExited
        MinimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/MinimizeButton.png")));
    }//GEN-LAST:event_MinimizeButtonMouseExited

    private void FullScreenButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonMouseMoved
        FullScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/FullScreenButton2.png")));
    }//GEN-LAST:event_FullScreenButtonMouseMoved

    private void FullScreenButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonMouseExited
        FullScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/FullScreenButton.png")));
    }//GEN-LAST:event_FullScreenButtonMouseExited

    private void DisposeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonMousePressed
        if (evt.getClickCount() >= 0) {
            this.dispose();
        } 
    }//GEN-LAST:event_DisposeButtonMousePressed

    private void MinimizeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMousePressed
        if (evt.getClickCount() >= 0) {
            this.setExtendedState(1);  
        } 
    }//GEN-LAST:event_MinimizeButtonMousePressed

    private void DisposeButtonWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonWMouseMoved
        DisposeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButtonW2.png")));
    }//GEN-LAST:event_DisposeButtonWMouseMoved

    private void DisposeButtonWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonWMouseExited
        DisposeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButtonW.png")));
    }//GEN-LAST:event_DisposeButtonWMouseExited

    private void FullScreenButtonWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonWMouseMoved
        FullScreenButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/FullScreenButtonW2.png")));
    }//GEN-LAST:event_FullScreenButtonWMouseMoved

    private void FullScreenButtonWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullScreenButtonWMouseExited
        FullScreenButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/FullScreenButtonW.png")));
    }//GEN-LAST:event_FullScreenButtonWMouseExited

    private void MinimizeButtonWMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonWMouseMoved
        MinimizeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/MinimizeButtonW2.png")));
    }//GEN-LAST:event_MinimizeButtonWMouseMoved

    private void MinimizeButtonWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonWMouseExited
         MinimizeButtonW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/MinimizeButtonW.png")));
    }//GEN-LAST:event_MinimizeButtonWMouseExited

    private void DisposeButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisposeButtonWMousePressed
        if (evt.getClickCount() >= 0) {
            this.dispose();
        } 
    }//GEN-LAST:event_DisposeButtonWMousePressed

    private void MinimizeButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonWMousePressed
        if (evt.getClickCount() >= 0) {
            this.setExtendedState(1);  
        } 
    }//GEN-LAST:event_MinimizeButtonWMousePressed

    private void CreateAccountBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountBtActionPerformed
        /*
        Crear cuenta
        */
    }//GEN-LAST:event_CreateAccountBtActionPerformed

    private void CreateAccountBtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountBtMouseMoved
        containerBtn.setBackground(new Color(53,163,31));
    }//GEN-LAST:event_CreateAccountBtMouseMoved

    private void CreateAccountBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountBtMouseExited
        containerBtn.setBackground(new Color(65,183,41));
    }//GEN-LAST:event_CreateAccountBtMouseExited

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_passwordFocusLost

    private void LogInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseExited
        containerBtnLog.setBackground(new Color(37,119,241));
    }//GEN-LAST:event_LogInBtnMouseExited

    private void LogInBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseMoved
        containerBtnLog.setBackground(new Color(35,111,229));
    }//GEN-LAST:event_LogInBtnMouseMoved

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        /*
        Iniciar sesion
        */
    }//GEN-LAST:event_LogInBtnActionPerformed

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        mail.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_mailFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        mail.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_mailFocusLost

    private void forgotMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseMoved
        Font font = forgot.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        forgot.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_forgotMouseMoved

    private void forgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseExited
        forgot.setFont(new Font("Arial", Font.BOLD, 13));
    }//GEN-LAST:event_forgotMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountBt;
    private javax.swing.JLabel DisposeButton;
    private javax.swing.JLabel DisposeButtonW;
    private javax.swing.JLabel FacebootLogo;
    private javax.swing.JLabel FullScreenButton;
    private javax.swing.JLabel FullScreenButtonW;
    private javax.swing.JLabel IniciarSesionCon;
    private javax.swing.JButton LogInBtn;
    private javax.swing.JLabel MinimizeButton;
    private javax.swing.JLabel MinimizeButtonW;
    private javax.swing.JLabel Title;
    public View.Components.RoundedPanel containerBtn;
    private View.Components.RoundedPanel containerBtnLog;
    private View.Components.RoundedPanel containerMail;
    private View.Components.RoundedPanel containerPassword;
    private javax.swing.JPanel content;
    private View.Components.RoundedPanel facebook;
    private javax.swing.JLabel forgot;
    private View.Components.RoundedPanel google;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private View.Components.RoundedPanel log;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel topBar;
    private View.Components.RoundedPanel twitter;
    // End of variables declaration//GEN-END:variables
}
