/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.panels;

import Faceboot.App;
import Faceboot.AppState;
import View.Components.TextPrompt;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.BorderFactory;

/**
 *
 * @author orlandocamacho
 */
public class LogInPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogInPanel
     */
    public LogInPanel() {
        initComponents();
        
        new TextPrompt("Correo electronico", mail);
        new TextPrompt("Contraseña", password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FacebootLogo = new javax.swing.JLabel();
        IniciarSesionCon = new javax.swing.JLabel();
        log = new View.Components.RoundedPanel();
        containerBtn = new View.Components.RoundedPanel();
        CreateAccountBt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        forgot = new javax.swing.JLabel();
        containerMail = new View.Components.RoundedPanel();
        mail = new javax.swing.JTextField();
        containerPassword = new View.Components.RoundedPanel();
        password = new javax.swing.JPasswordField();
        containerBtnLog = new View.Components.RoundedPanel();
        LogInBtn = new javax.swing.JButton();
        facebook = new View.Components.RoundedPanel();
        btnFacebook = new javax.swing.JButton();
        twitter = new View.Components.RoundedPanel();
        btnTwitter = new javax.swing.JButton();
        google = new View.Components.RoundedPanel();
        btnGoogle = new javax.swing.JButton();

        setBackground(new java.awt.Color(23, 24, 26));

        FacebootLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FacebootLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/faceboot2.png"))); // NOI18N

        IniciarSesionCon.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        IniciarSesionCon.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesionCon.setText("Iniciar sesión con:");

        log.setBackground(new java.awt.Color(35, 36, 37));
        log.setForeground(new java.awt.Color(255, 255, 255));

        containerBtn.setBackground(new java.awt.Color(65, 183, 41));
        containerBtn.setLayout(new java.awt.BorderLayout());

        CreateAccountBt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CreateAccountBt.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountBt.setText("Crear cuenta nueva");
        CreateAccountBt.setContentAreaFilled(false);
        CreateAccountBt.setFocusPainted(false);
        CreateAccountBt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CreateAccountBtMouseMoved(evt);
            }
        });
        CreateAccountBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateAccountBtMouseExited(evt);
            }
        });
        CreateAccountBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountBtActionPerformed(evt);
            }
        });
        containerBtn.add(CreateAccountBt, java.awt.BorderLayout.CENTER);

        forgot.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        forgot.setForeground(new java.awt.Color(37, 119, 241));
        forgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgot.setText("¿Olvidaste tu contraseña?");
        forgot.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgotMouseMoved(evt);
            }
        });
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotMouseExited(evt);
            }
        });

        containerMail.setBackground(new java.awt.Color(58, 59, 60));
        containerMail.setToolTipText("Correo electrónico");

        mail.setBackground(new java.awt.Color(58, 59, 60));
        mail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        mail.setForeground(new java.awt.Color(204, 204, 204));
        mail.setToolTipText("");
        mail.setBorder(null);
        mail.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerMailLayout = new javax.swing.GroupLayout(containerMail);
        containerMail.setLayout(containerMailLayout);
        containerMailLayout.setHorizontalGroup(
            containerMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMailLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerMailLayout.setVerticalGroup(
            containerMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerMailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerPassword.setBackground(new java.awt.Color(58, 59, 60));
        containerPassword.setToolTipText("Contraseña");

        password.setBackground(new java.awt.Color(58, 59, 60));
        password.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setToolTipText("");
        password.setBorder(null);
        password.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerPasswordLayout = new javax.swing.GroupLayout(containerPassword);
        containerPassword.setLayout(containerPasswordLayout);
        containerPasswordLayout.setHorizontalGroup(
            containerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPasswordLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPasswordLayout.setVerticalGroup(
            containerPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerBtnLog.setBackground(new java.awt.Color(37, 119, 241));
        containerBtnLog.setLayout(new java.awt.BorderLayout());

        LogInBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogInBtn.setText("Iniciar sesión");
        LogInBtn.setContentAreaFilled(false);
        LogInBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogInBtnMouseMoved(evt);
            }
        });
        LogInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInBtnMouseExited(evt);
            }
        });
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });
        containerBtnLog.add(LogInBtn, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout logLayout = new javax.swing.GroupLayout(log);
        log.setLayout(logLayout);
        logLayout.setHorizontalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(containerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(containerBtnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containerPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(containerMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, logLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(forgot, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        logLayout.setVerticalGroup(
            logLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(containerMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(containerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(containerBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(forgot)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(containerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        facebook.setBackground(new java.awt.Color(37, 119, 241));
        facebook.setLayout(new java.awt.BorderLayout());

        btnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/facebookLogin.png"))); // NOI18N
        btnFacebook.setContentAreaFilled(false);
        btnFacebook.setPreferredSize(new java.awt.Dimension(64, 64));
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });
        facebook.add(btnFacebook, java.awt.BorderLayout.PAGE_END);

        twitter.setBackground(new java.awt.Color(45, 163, 226));
        twitter.setLayout(new java.awt.BorderLayout());

        btnTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/twitterLogin.png"))); // NOI18N
        btnTwitter.setContentAreaFilled(false);
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });
        twitter.add(btnTwitter, java.awt.BorderLayout.CENTER);

        google.setBackground(new java.awt.Color(255, 255, 255));
        google.setLayout(new java.awt.BorderLayout());

        btnGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/googleLogin.png"))); // NOI18N
        btnGoogle.setContentAreaFilled(false);
        btnGoogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoogleActionPerformed(evt);
            }
        });
        google.add(btnGoogle, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FacebootLogo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(IniciarSesionCon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(facebook, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(google, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FacebootLogo)
                        .addGap(15, 15, 15)
                        .addComponent(IniciarSesionCon)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(google, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(facebook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccountBtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountBtMouseMoved
        containerBtn.setBackground(new Color(53,163,31));
    }//GEN-LAST:event_CreateAccountBtMouseMoved

    private void CreateAccountBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountBtMouseExited
        containerBtn.setBackground(new Color(65,183,41));
    }//GEN-LAST:event_CreateAccountBtMouseExited

    private void CreateAccountBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountBtActionPerformed

        App.GetSingleton().SetState(AppState.Register);
    }//GEN-LAST:event_CreateAccountBtActionPerformed

    private void forgotMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseMoved
        Font font = forgot.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        forgot.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_forgotMouseMoved

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked

    }//GEN-LAST:event_forgotMouseClicked

    private void forgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseExited
        forgot.setFont(new Font("Arial", Font.BOLD, 13));
    }//GEN-LAST:event_forgotMouseExited

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        mail.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_mailFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        mail.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_mailFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_passwordFocusLost

    private void LogInBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseMoved
        containerBtnLog.setBackground(new Color(35,111,229));
    }//GEN-LAST:event_LogInBtnMouseMoved

    private void LogInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBtnMouseExited
        containerBtnLog.setBackground(new Color(37,119,241));
    }//GEN-LAST:event_LogInBtnMouseExited

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        String email = mail.getText();
        String password = new String(this.password.getPassword());
        App.GetSingleton().LoginController.AttemptLogin(email, password);
    }//GEN-LAST:event_LogInBtnActionPerformed

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        // TODO: AGREGAR LOGIN DE FB
        String email = mail.getText();
        String password = new String(this.password.getPassword());
        App.GetSingleton().LoginController.AttemptLogin(email, password);
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
        // TODO: AGREGAR LOGIN DE Twitter
        String email = mail.getText();
        String password = new String(this.password.getPassword());
        App.GetSingleton().LoginController.AttemptLogin(email, password);
    }//GEN-LAST:event_btnTwitterActionPerformed

    private void btnGoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoogleActionPerformed
        // TODO add your handling code here:
        // TODO: AGREGAR LOGIN DE Google
        String email = mail.getText();
        String password = new String(this.password.getPassword());
        App.GetSingleton().LoginController.AttemptLogin(email, password);
    }//GEN-LAST:event_btnGoogleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountBt;
    private javax.swing.JLabel FacebootLogo;
    private javax.swing.JLabel IniciarSesionCon;
    private javax.swing.JButton LogInBtn;
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnGoogle;
    private javax.swing.JButton btnTwitter;
    public View.Components.RoundedPanel containerBtn;
    private View.Components.RoundedPanel containerBtnLog;
    private View.Components.RoundedPanel containerMail;
    private View.Components.RoundedPanel containerPassword;
    private View.Components.RoundedPanel facebook;
    private javax.swing.JLabel forgot;
    private View.Components.RoundedPanel google;
    private javax.swing.JSeparator jSeparator1;
    private View.Components.RoundedPanel log;
    private javax.swing.JTextField mail;
    private javax.swing.JPasswordField password;
    private View.Components.RoundedPanel twitter;
    // End of variables declaration//GEN-END:variables
}
