/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Components;

import FacebootNet.Packets.Server.EPostStruct;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author orlandocamacho
 */
public class Comment extends javax.swing.JPanel {
    
    /**
     * Creates new form Post
     */
    public Comment() {
        this.setBackground(new Color(255,255,255,0));
        this.setOpaque(false);
        initComponents();
        this.text.setLineWrap(true);
        this.text.setWrapStyleWord(true);
        this.setSize(734, 125);
    }
    
    public void mapPost(EPostStruct post){
        this.username.setText(post.UserName);
        this.time.setText(new Date(post.PostTime).toString());            
        this.text.setText(post.PostBody);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        post = new View.Components.RoundedPanel();
        containerUser4 = new View.Components.RoundPanelText();
        user4 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        roundedPanel1 = new View.Components.RoundedPanel();
        username = new javax.swing.JLabel();
        text = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(23, 24, 26));
        setPreferredSize(new java.awt.Dimension(734, 287));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        post.setBackground(new java.awt.Color(35, 36, 37));
        post.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerUser4.setBackground(new java.awt.Color(58, 59, 60));
        containerUser4.setLayout(new java.awt.BorderLayout());

        user4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/user.png"))); // NOI18N
        user4.setContentAreaFilled(false);
        user4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        containerUser4.add(user4, java.awt.BorderLayout.CENTER);

        post.add(containerUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        time.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        time.setForeground(new java.awt.Color(153, 153, 153));
        time.setText("11 h");
        post.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 95, -1, 20));

        roundedPanel1.setBackground(new java.awt.Color(58, 59, 60));
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Usuario #1");
        roundedPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        text.setBackground(new java.awt.Color(58, 59, 60));
        text.setColumns(20);
        text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setRows(5);
        text.setText("feoiuf bypwe9ugfhnp w9ugfhbpy w9eygfpw98nfpwy8fb pe08ifwn8p0e8fywb`08fncw`08efm w0e8y\nf bew98gy breiugt bowe79yrbw p97rncw9e7rb cwoe7rrb wo39r37wguw3wr");
        text.setToolTipText("");
        text.setBorder(null);
        text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFocusLost(evt);
            }
        });
        text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textKeyTyped(evt);
            }
        });
        roundedPanel1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, 620, 40));

        post.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 640, 85));

        add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 125));
    }// </editor-fold>//GEN-END:initComponents

    private void textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFocusGained
        if (text.getText().equals("¿Qué estás pensando?")) {
            text.setText("");
        }
    }//GEN-LAST:event_textFocusGained

    private void textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFocusLost
        if (text.getText().equals("")){
            text.setText("¿Qué estás pensando?");
        }
    }//GEN-LAST:event_textFocusLost

    private void textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textKeyTyped
        if (text.getText().length() == 250)
        evt.consume();
    }//GEN-LAST:event_textKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.Components.RoundPanelText containerUser4;
    private View.Components.RoundedPanel post;
    private View.Components.RoundedPanel roundedPanel1;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel time;
    private javax.swing.JButton user4;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
