/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Components;

import FacebootNet.Packets.Server.EPostStruct;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author orlandocamacho
 */
public class PostWithAttachments extends javax.swing.JPanel {
    
    /**
     * Creates new form Post
     */
    public PostWithAttachments() {
        this.setBackground(new Color(255,255,255,0));
        this.setOpaque(false);
        initComponents();
        new TextPrompt("Escribe un comentario...", commentField );
        this.setSize(734, 670);
    }
    
    public void mapPost(EPostStruct post){
        this.username.setText(post.UserName);
        this.time.setText(new Date(post.PostTime).toString());            
        this.text.setText(post.PostBody);
        this.image.setText(post.HasAttachment+"");
        this.totalComments.setText(post.TotalComments + " comentarios");
        this.totalReactions.setText(String.valueOf(post.TotalLikes));
        this.deleteBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        post = new View.Components.RoundedPanel();
        containerUser4 = new View.Components.RoundPanelText();
        user4 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        totalReactions = new javax.swing.JLabel();
        totalComments = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        containerComment = new View.Components.RoundedPanel();
        addComment = new javax.swing.JButton();
        containerLike = new View.Components.RoundedPanel();
        likeButton = new javax.swing.JToggleButton();
        containerUser2 = new View.Components.RoundPanelText();
        user2 = new javax.swing.JButton();
        containerCommentField = new View.Components.RoundPanelText();
        commentField = new javax.swing.JTextField();
        containerDetele = new View.Components.RoundPanelText();
        deleteBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(23, 24, 26));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        post.setBackground(new java.awt.Color(35, 36, 37));
        post.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerUser4.setBackground(new java.awt.Color(58, 59, 60));
        containerUser4.setLayout(new java.awt.BorderLayout());

        user4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/user.png"))); // NOI18N
        user4.setContentAreaFilled(false);
        user4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        containerUser4.add(user4, java.awt.BorderLayout.CENTER);

        post.add(containerUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Usuario #1");
        post.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        time.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        time.setForeground(new java.awt.Color(153, 153, 153));
        time.setText("11 h");
        post.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        text.setText("<html> fboawu foawufg oauwgfoauw gfoauw foawug foauwg foaugwfo awufo waufgao uwgf aouwgfo aufoa uwgfoau fgoawu gfouag wof awouf goauwgfoau wgfouawg foauwg foaugwf ouagw oauwg foaug foawug foauwgfoawug fowaug foauwgfoawugfoaw ugoaw wofuagwofu fawugfwaoufgw f </html>");
        text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        post.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 694, 60));

        image.setBackground(new java.awt.Color(58, 59, 60));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/DisposeButton.png"))); // NOI18N
        image.setOpaque(true);
        post.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, 734, 370));
        post.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 694, -1));

        totalReactions.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalReactions.setForeground(new java.awt.Color(153, 153, 153));
        totalReactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likes.png"))); // NOI18N
        totalReactions.setText("2");
        totalReactions.setIconTextGap(10);
        post.add(totalReactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        totalComments.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalComments.setForeground(new java.awt.Color(153, 153, 153));
        totalComments.setText("2 comentarios");
        post.add(totalComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));
        post.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 694, -1));

        containerComment.setBackground(new java.awt.Color(35, 36, 37));
        containerComment.setLayout(new java.awt.BorderLayout());

        addComment.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addComment.setForeground(new java.awt.Color(153, 153, 153));
        addComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/comment.png"))); // NOI18N
        addComment.setText("Comentar");
        addComment.setContentAreaFilled(false);
        addComment.setIconTextGap(10);
        addComment.setPreferredSize(new java.awt.Dimension(122, 30));
        addComment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addCommentMouseMoved(evt);
            }
        });
        addComment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCommentMouseExited(evt);
            }
        });
        addComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentActionPerformed(evt);
            }
        });
        containerComment.add(addComment, java.awt.BorderLayout.PAGE_END);

        post.add(containerComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 200, -1));

        containerLike.setBackground(new java.awt.Color(35, 36, 37));
        containerLike.setLayout(new java.awt.BorderLayout());

        likeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        likeButton.setForeground(new java.awt.Color(153, 153, 153));
        likeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likeOff.png"))); // NOI18N
        likeButton.setText("Me gusta");
        likeButton.setContentAreaFilled(false);
        likeButton.setIconTextGap(10);
        likeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likeOff.png"))); // NOI18N
        likeButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likeOn.png"))); // NOI18N
        likeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                likeButtonMouseMoved(evt);
            }
        });
        likeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                likeButtonMouseExited(evt);
            }
        });
        likeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeButtonActionPerformed(evt);
            }
        });
        containerLike.add(likeButton, java.awt.BorderLayout.CENTER);

        post.add(containerLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 200, 30));

        containerUser2.setBackground(new java.awt.Color(58, 59, 60));
        containerUser2.setLayout(new java.awt.BorderLayout());

        user2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/user.png"))); // NOI18N
        user2.setContentAreaFilled(false);
        user2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        containerUser2.add(user2, java.awt.BorderLayout.CENTER);

        post.add(containerUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 615, 40, 40));

        containerCommentField.setBackground(new java.awt.Color(58, 59, 60));

        commentField.setBackground(new java.awt.Color(58, 59, 60));
        commentField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        commentField.setForeground(new java.awt.Color(204, 204, 204));
        commentField.setBorder(null);
        commentField.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        commentField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                commentFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                commentFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout containerCommentFieldLayout = new javax.swing.GroupLayout(containerCommentField);
        containerCommentField.setLayout(containerCommentFieldLayout);
        containerCommentFieldLayout.setHorizontalGroup(
            containerCommentFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCommentFieldLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(commentField, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        containerCommentFieldLayout.setVerticalGroup(
            containerCommentFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCommentFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(commentField, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        post.add(containerCommentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 615, -1, -1));

        containerDetele.setBackground(new java.awt.Color(35, 36, 37));
        containerDetele.setLayout(new java.awt.BorderLayout());

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/delete.png"))); // NOI18N
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteBtnMouseMoved(evt);
            }
        });
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        containerDetele.add(deleteBtn, java.awt.BorderLayout.CENTER);

        post.add(containerDetele, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 12, 35, 35));

        add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void addCommentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCommentMouseMoved
        containerComment.setBackground(new Color(58,59,60));
    }//GEN-LAST:event_addCommentMouseMoved

    private void addCommentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCommentMouseExited
        containerComment.setBackground(new Color(35,36,37));
    }//GEN-LAST:event_addCommentMouseExited

    private void likeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeButtonMouseExited
        containerLike.setBackground(new Color(35,36,37));
    }//GEN-LAST:event_likeButtonMouseExited

    private void likeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeButtonMouseMoved
        containerLike.setBackground(new Color(58,59,60));
    }//GEN-LAST:event_likeButtonMouseMoved

    private void likeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonActionPerformed
        if (likeButton.isSelected()){
            likeButton.setForeground(new Color(60,135,243));
        } else {
            likeButton.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_likeButtonActionPerformed

    private void addCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentActionPerformed
        commentField.requestFocus();
    }//GEN-LAST:event_addCommentActionPerformed

    private void commentFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commentFieldKeyTyped
        if (commentField.getText().length() == 250)
        evt.consume();
    }//GEN-LAST:event_commentFieldKeyTyped

    private void deleteBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseMoved
        containerDetele.setBackground(new Color(58,59,60));
    }//GEN-LAST:event_deleteBtnMouseMoved

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        containerDetele.setBackground(new Color(35,36,37));
    }//GEN-LAST:event_deleteBtnMouseExited

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // delete post
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void commentFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_commentFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (commentField.getText() != "") {
                commentField.setText("");
                // Enviar el comentario
            }
        }
    }//GEN-LAST:event_commentFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComment;
    private javax.swing.JTextField commentField;
    private View.Components.RoundedPanel containerComment;
    private View.Components.RoundPanelText containerCommentField;
    private View.Components.RoundPanelText containerDetele;
    private View.Components.RoundedPanel containerLike;
    private View.Components.RoundPanelText containerUser2;
    private View.Components.RoundPanelText containerUser4;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel image;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton likeButton;
    private View.Components.RoundedPanel post;
    private javax.swing.JLabel text;
    private javax.swing.JLabel time;
    private javax.swing.JLabel totalComments;
    private javax.swing.JLabel totalReactions;
    private javax.swing.JButton user2;
    private javax.swing.JButton user4;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
