/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Components;

import FacebootNet.Packets.Server.EPostStruct;
import java.awt.Color;
import java.util.Date;

/**
 *
 * @author orlandocamacho
 */
public class Post extends javax.swing.JPanel {

    /**
     * Creates new form Post
     */
    public Post() {
        this.setBackground(new Color(255,255,255,0));
        this.setOpaque(false);
        initComponents();
    }
    
    public void mapPost(EPostStruct post){
        this.username.setText(post.UserName);
        this.time.setText(new Date(post.PostTime).toString());
        this.text.setText(post.PostBody);
        this.totalComments.setText(post.TotalComments + " comentarios");
        this.totalReactions.setText(String.valueOf(post.TotalLikes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        post = new View.Components.RoundedPanel();
        containerUser2 = new View.Components.RoundPanelText();
        user2 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        totalReactions = new javax.swing.JLabel();
        totalComments = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        containerComment = new View.Components.RoundedPanel();
        addComment = new javax.swing.JButton();
        containerLike = new View.Components.RoundedPanel();
        likeButton = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(23, 24, 26));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        post.setBackground(new java.awt.Color(35, 36, 37));
        post.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerUser2.setBackground(new java.awt.Color(58, 59, 60));
        containerUser2.setLayout(new java.awt.BorderLayout());

        user2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/user.png"))); // NOI18N
        user2.setContentAreaFilled(false);
        user2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        containerUser2.add(user2, java.awt.BorderLayout.CENTER);

        post.add(containerUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Usuario #1");
        post.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 20));

        time.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        time.setForeground(new java.awt.Color(153, 153, 153));
        time.setText("11 h");
        post.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        text.setText("<html> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam dolor, suscipit malesuada suscipit id, rhoncus a nunc. Curabitur nec nunc eget odio vehicula cursus. Duis at accumsan purus. Sed odio risus, ultrices eget nunc at, varius auctor nisi. Morbi sed posuere ipsum, id tempor neque. Morbi pretium ex risus, sed imperdiet eros rhoncus a. Nulla facilisi. Fusce tincidunt tortor ut est aliquet, ac mattis libero pharetra. Integer quis faucibus turpis, sit amet tincidunt eros. </html>");
        text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        post.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 694, 90));
        post.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 694, 3));

        totalReactions.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalReactions.setForeground(new java.awt.Color(153, 153, 153));
        totalReactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likes.png"))); // NOI18N
        totalReactions.setText("2");
        totalReactions.setIconTextGap(10);
        post.add(totalReactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        totalComments.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        totalComments.setForeground(new java.awt.Color(153, 153, 153));
        totalComments.setText("2 comentarios");
        post.add(totalComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 190, 90, -1));
        post.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 225, 694, 3));

        containerComment.setBackground(new java.awt.Color(35, 36, 37));
        containerComment.setLayout(new java.awt.BorderLayout());

        addComment.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addComment.setForeground(new java.awt.Color(153, 153, 153));
        addComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/comment.png"))); // NOI18N
        addComment.setText("Comentar");
        addComment.setContentAreaFilled(false);
        addComment.setIconTextGap(10);
        addComment.setPreferredSize(new java.awt.Dimension(122, 30));
        addComment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addCommentMouseMoved(evt);
            }
        });
        addComment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCommentMouseExited(evt);
            }
        });
        containerComment.add(addComment, java.awt.BorderLayout.PAGE_END);

        post.add(containerComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, 30));

        containerLike.setBackground(new java.awt.Color(35, 36, 37));
        containerLike.setLayout(new java.awt.BorderLayout());

        likeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        likeButton.setForeground(new java.awt.Color(153, 153, 153));
        likeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likeOff.png"))); // NOI18N
        likeButton.setText("Me gusta");
        likeButton.setContentAreaFilled(false);
        likeButton.setIconTextGap(10);
        likeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likeOff.png"))); // NOI18N
        likeButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/likeOn.png"))); // NOI18N
        likeButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                likeButtonMouseMoved(evt);
            }
        });
        likeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                likeButtonMouseExited(evt);
            }
        });
        likeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeButtonActionPerformed(evt);
            }
        });
        containerLike.add(likeButton, java.awt.BorderLayout.CENTER);

        post.add(containerLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 30));

        add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void addCommentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCommentMouseMoved
        containerComment.setBackground(new Color(58,59,60));
    }//GEN-LAST:event_addCommentMouseMoved

    private void addCommentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCommentMouseExited
        containerComment.setBackground(new Color(35,36,37));
    }//GEN-LAST:event_addCommentMouseExited

    private void likeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeButtonMouseExited
        containerLike.setBackground(new Color(35,36,37));
    }//GEN-LAST:event_likeButtonMouseExited

    private void likeButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeButtonMouseMoved
        containerLike.setBackground(new Color(58,59,60));
    }//GEN-LAST:event_likeButtonMouseMoved

    private void likeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeButtonActionPerformed
        if (likeButton.isSelected()){
            likeButton.setForeground(new Color(60,135,243));
        } else {
            likeButton.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_likeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComment;
    private View.Components.RoundedPanel containerComment;
    private View.Components.RoundedPanel containerLike;
    private View.Components.RoundPanelText containerUser2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton likeButton;
    private View.Components.RoundedPanel post;
    private javax.swing.JLabel text;
    private javax.swing.JLabel time;
    private javax.swing.JLabel totalComments;
    private javax.swing.JLabel totalReactions;
    private javax.swing.JButton user2;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
