/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Components;

import Faceboot.App;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;

/**
 *
 * @author orlandocamacho
 */
public class RegisterModal extends javax.swing.JDialog {

    
    /**
     * Creates new form RegisterModal
     * @param parent
     * @param modal
     */
    public RegisterModal(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        this.setUndecorated(true);
        super.setUndecorated(true);
        
        setShape(new RoundRectangle2D.Double(0, 0, 430, 550,22,22));
        initComponents();
        
        new TextPrompt("Nombre", name);
        new TextPrompt("Apellido", lastname);
        new TextPrompt("Correo electrónico", email);
        new TextPrompt("Contraseña", password);
        
        setLocationRelativeTo(null);
        
        comboboxSetInvisible();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel = new View.Components.RoundedPanel();
        register = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        isfast = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        containerName80 = new View.Components.RoundedPanel();
        cYear = new javax.swing.JComboBox<>();
        containerName81 = new View.Components.RoundedPanel();
        female11 = new javax.swing.JRadioButton();
        containerName82 = new View.Components.RoundedPanel();
        personalized11 = new javax.swing.JRadioButton();
        jLabel35 = new javax.swing.JLabel();
        containerName83 = new View.Components.RoundedPanel();
        cDay = new javax.swing.JComboBox<>();
        containerName84 = new View.Components.RoundedPanel();
        cMonth = new javax.swing.JComboBox<>();
        containerName85 = new View.Components.RoundedPanel();
        male11 = new javax.swing.JRadioButton();
        containerBtn12 = new View.Components.RoundedPanel();
        signUp = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        containerName86 = new View.Components.RoundedPanel();
        password = new javax.swing.JPasswordField();
        containerName1 = new View.Components.RoundedPanel();
        lastname = new javax.swing.JTextField();
        containerName2 = new View.Components.RoundedPanel();
        email = new javax.swing.JTextField();
        containerName = new View.Components.RoundedPanel();
        name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        roundedPanel.setBackground(new java.awt.Color(23, 24, 26));
        roundedPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("Registrarte");
        roundedPanel.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/x.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closecloseMousePressed(evt);
            }
        });
        roundedPanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        isfast.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        isfast.setForeground(new java.awt.Color(255, 255, 255));
        isfast.setText("Es rápido y fácil.");
        roundedPanel.add(isfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 62, -1, 20));

        jLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("<html>\nAl hacer clic en \"Registrarte\", aceptas nuestras Condiciones, la Política de\ndatos y la Política de cookies. Es posible que te enviemos notificaciones por \nSMS, que puedes desactivar cuando quieras.\n</html>"); // NOI18N
        roundedPanel.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 390, 40));
        roundedPanel.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 430, 10));

        containerName80.setBackground(new java.awt.Color(58, 59, 60));
        containerName80.setToolTipText("Correo electrónico");
        containerName80.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cYear.setBackground(new java.awt.Color(58, 59, 60));
        cYear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cYear.setForeground(new java.awt.Color(204, 204, 204));
        cYear.setMaximumRowCount(10);
        cYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cYear.setBorder(null);
        containerName80.add(cYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        roundedPanel.add(containerName80, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 120, 40));

        containerName81.setBackground(new java.awt.Color(58, 59, 60));
        containerName81.setToolTipText("Correo electrónico");
        containerName81.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        female11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        female11.setForeground(new java.awt.Color(204, 204, 204));
        female11.setText("Mujer");
        female11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        female11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        female11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButton.png"))); // NOI18N
        female11.setIconTextGap(25);
        female11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonHover.png"))); // NOI18N
        female11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonSelected.png"))); // NOI18N
        containerName81.add(female11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        roundedPanel.add(containerName81, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 40));

        containerName82.setBackground(new java.awt.Color(58, 59, 60));
        containerName82.setToolTipText("Correo electrónico");
        containerName82.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personalized11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        personalized11.setForeground(new java.awt.Color(204, 204, 204));
        personalized11.setText("Personalizado");
        personalized11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personalized11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        personalized11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButton.png"))); // NOI18N
        personalized11.setIconTextGap(21);
        personalized11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonHover.png"))); // NOI18N
        personalized11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonSelected.png"))); // NOI18N
        containerName82.add(personalized11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        roundedPanel.add(containerName82, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 150, 40));

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Sexo");
        roundedPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        containerName83.setBackground(new java.awt.Color(58, 59, 60));
        containerName83.setToolTipText("Correo electrónico");
        containerName83.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cDay.setBackground(new java.awt.Color(58, 59, 60));
        cDay.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cDay.setForeground(new java.awt.Color(255, 255, 255));
        cDay.setMaximumRowCount(10);
        cDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cDay.setBorder(null);
        containerName83.add(cDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        roundedPanel.add(containerName83, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 40));

        containerName84.setBackground(new java.awt.Color(58, 59, 60));
        containerName84.setToolTipText("Correo electrónico");
        containerName84.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cMonth.setBackground(new java.awt.Color(58, 59, 60));
        cMonth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cMonth.setForeground(new java.awt.Color(204, 204, 204));
        cMonth.setMaximumRowCount(10);
        cMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cMonth.setBorder(null);
        containerName84.add(cMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        roundedPanel.add(containerName84, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 130, 40));

        containerName85.setBackground(new java.awt.Color(58, 59, 60));
        containerName85.setToolTipText("Correo electrónico");
        containerName85.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        male11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        male11.setForeground(new java.awt.Color(204, 204, 204));
        male11.setText("Hombre");
        male11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        male11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        male11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButton.png"))); // NOI18N
        male11.setIconTextGap(30);
        male11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonHover.png"))); // NOI18N
        male11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/RadioButtonSelected.png"))); // NOI18N
        containerName85.add(male11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        roundedPanel.add(containerName85, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 120, 40));

        containerBtn12.setBackground(new java.awt.Color(65, 183, 41));
        containerBtn12.setLayout(new java.awt.BorderLayout());

        signUp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        signUp.setForeground(new java.awt.Color(255, 255, 255));
        signUp.setText("Registrarte");
        signUp.setContentAreaFilled(false);
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        containerBtn12.add(signUp, java.awt.BorderLayout.CENTER);

        roundedPanel.add(containerBtn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 190, 35));

        jLabel36.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Fecha de nacimiento");
        roundedPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        containerName86.setBackground(new java.awt.Color(58, 59, 60));
        containerName86.setToolTipText("Correo electrónico");

        password.setBackground(new java.awt.Color(58, 59, 60));
        password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setToolTipText("");
        password.setBorder(null);
        password.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordpasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerName86Layout = new javax.swing.GroupLayout(containerName86);
        containerName86.setLayout(containerName86Layout);
        containerName86Layout.setHorizontalGroup(
            containerName86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName86Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        containerName86Layout.setVerticalGroup(
            containerName86Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName86Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel.add(containerName86, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 40));

        containerName1.setBackground(new java.awt.Color(58, 59, 60));
        containerName1.setToolTipText("Correo electrónico");

        lastname.setBackground(new java.awt.Color(58, 59, 60));
        lastname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(204, 204, 204));
        lastname.setBorder(null);
        lastname.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerName1Layout = new javax.swing.GroupLayout(containerName1);
        containerName1.setLayout(containerName1Layout);
        containerName1Layout.setHorizontalGroup(
            containerName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        containerName1Layout.setVerticalGroup(
            containerName1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel.add(containerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 190, 40));

        containerName2.setBackground(new java.awt.Color(58, 59, 60));
        containerName2.setToolTipText("Correo electrónico");

        email.setBackground(new java.awt.Color(58, 59, 60));
        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setToolTipText("");
        email.setBorder(null);
        email.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerName2Layout = new javax.swing.GroupLayout(containerName2);
        containerName2.setLayout(containerName2Layout);
        containerName2Layout.setHorizontalGroup(
            containerName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerName2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        containerName2Layout.setVerticalGroup(
            containerName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerName2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel.add(containerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 390, 40));

        containerName.setBackground(new java.awt.Color(58, 59, 60));
        containerName.setToolTipText("Correo electrónico");

        name.setBackground(new java.awt.Color(58, 59, 60));
        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        name.setBorder(null);
        name.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });

        javax.swing.GroupLayout containerNameLayout = new javax.swing.GroupLayout(containerName);
        containerName.setLayout(containerNameLayout);
        containerNameLayout.setHorizontalGroup(
            containerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerNameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        containerNameLayout.setVerticalGroup(
            containerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedPanel.add(containerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closecloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closecloseMousePressed
        if (evt.getClickCount() >= 0) {
            this.dispose();
        }
    }//GEN-LAST:event_closecloseMousePressed

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        String name = this.name.getText();
        String lastName = this.lastname.getText();
        String email = this.email.getText();
        String password = new String(this.password.getPassword());
        App.GetSingleton().RegisterController.AttemptRegister(name, lastName, email, password);
    }//GEN-LAST:event_signUpActionPerformed

    private void passwordpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordpasswordFocusGained
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_passwordpasswordFocusGained

    private void passwordpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordpasswordFocusLost
        password.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_passwordpasswordFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        lastname.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        lastname.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_lastnameFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        email.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        email.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_emailFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(37,119,241)));
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        name.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(58,59,60)));
    }//GEN-LAST:event_nameFocusLost

    public void comboboxSetInvisible(){
        cDay.setOpaque(false);
        cDay.setBackground(new Color(0,0,0,0));
        cDay.setForeground(Color.WHITE);
        cMonth.setOpaque(false);
        cMonth.setBackground(new Color(0,0,0,0));
        cYear.setOpaque(false);
        cYear.setBackground(new Color(0,0,0,0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cDay;
    private javax.swing.JComboBox<String> cMonth;
    private javax.swing.JComboBox<String> cYear;
    private javax.swing.JLabel close;
    public View.Components.RoundedPanel containerBtn12;
    private View.Components.RoundedPanel containerName;
    private View.Components.RoundedPanel containerName1;
    private View.Components.RoundedPanel containerName2;
    private View.Components.RoundedPanel containerName80;
    private View.Components.RoundedPanel containerName81;
    private View.Components.RoundedPanel containerName82;
    private View.Components.RoundedPanel containerName83;
    private View.Components.RoundedPanel containerName84;
    private View.Components.RoundedPanel containerName85;
    private View.Components.RoundedPanel containerName86;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female11;
    private javax.swing.JLabel isfast;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton male11;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton personalized11;
    private javax.swing.JLabel register;
    private View.Components.RoundedPanel roundedPanel;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
