/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Components;

import FacebootNet.Packets.Server.EPostStruct;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 *
 * @author orlandocamacho
 */
public class SearchNotFound extends javax.swing.JPanel {
    
    /**
     * Creates new form Post
     */
    public SearchNotFound() {
        this.setBackground(new Color(255,255,255,0));
        this.setOpaque(false);
        initComponents();
        this.setSize(734, 100);
    }
    
    public void mapPost(EPostStruct post){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        post = new View.Components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 24, 26));
        setPreferredSize(new java.awt.Dimension(734, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        post.setBackground(new java.awt.Color(23, 24, 26));
        post.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/searchNotFound.png"))); // NOI18N
        post.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 10, 530, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No se encontró ningun resultado que coincida con esta busqueda");
        post.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 530, -1));

        add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private View.Components.RoundedPanel post;
    // End of variables declaration//GEN-END:variables
}
