/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Components;

import java.awt.Color;

/**
 *
 * @author orlandocamacho
 */
public class UserChat extends javax.swing.JPanel {

    /**
     * Creates new form UserChat
     */
    public UserChat() {
        this.setBackground(new Color(255,255,255,0));
        this.setOpaque(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userContainer = new View.Components.RoundedPanel();
        chatUser = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userContainer.setBackground(new java.awt.Color(23, 24, 26));
        userContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chatUser.setForeground(new java.awt.Color(204, 204, 204));
        chatUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/UserChatIcon.png"))); // NOI18N
        chatUser.setText("Usuario #");
        chatUser.setContentAreaFilled(false);
        chatUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chatUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chatUser.setIconTextGap(10);
        chatUser.setMargin(new java.awt.Insets(2, 0, 2, 14));
        chatUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                chatUserMouseMoved(evt);
            }
        });
        chatUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chatUserMouseExited(evt);
            }
        });
        userContainer.add(chatUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 200, 40));

        add(userContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void chatUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatUserMouseMoved
        userContainer.setBackground(new Color(35,36,37));
    }//GEN-LAST:event_chatUserMouseMoved

    private void chatUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatUserMouseExited
        userContainer.setBackground(new Color(23,24,26));
    }//GEN-LAST:event_chatUserMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chatUser;
    private View.Components.RoundedPanel userContainer;
    // End of variables declaration//GEN-END:variables
}
